// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using NoBadClothes;
using System;

namespace NoBadClothes.Migrations
{
    [DbContext(typeof(NoBadContext))]
    partial class NoBadContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("NoBadClothes.Station", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<double>("Latitude");

                    b.Property<double>("Longitude");

                    b.Property<string>("Name");

                    b.Property<DateTime>("ReferenceTime");

                    b.HasKey("Id");

                    b.ToTable("Stations");
                });

            modelBuilder.Entity("NoBadClothes.Weather", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("PrecipationCategory");

                    b.Property<double>("PrecipationMean");

                    b.Property<int?>("StationId");

                    b.Property<double>("Temperature");

                    b.Property<DateTime>("Time");

                    b.Property<int>("WeatherSymbol");

                    b.Property<int>("WindDirection");

                    b.Property<double>("WindGust");

                    b.Property<double>("WindSpeed");

                    b.HasKey("Id");

                    b.HasIndex("StationId");

                    b.ToTable("Weathers");
                });

            modelBuilder.Entity("NoBadClothes.Weather", b =>
                {
                    b.HasOne("NoBadClothes.Station", "Station")
                        .WithMany("WeatherForecast")
                        .HasForeignKey("StationId");
                });
#pragma warning restore 612, 618
        }
    }
}
